### PR TITLE
Pip

### PR DESCRIPTION
**Pull request by creepinson**
Changes:

- Migrated to pip package
- Formatted
- Added support for multiple domains
- Added default options if not specified
- Added reload configuration yes/no option

### CODE REVIEW

**Comment by creepinson** [comment]
Well it looks like deleting start.py and moving it to apache_dcg folder made the merge error so if you approve it you might have to do it via command line.

**Comment by onyxcode** [comment]
**_help me_**

**Comment by creepinson** [comment]
I got an error as well I think you need to use the command line...
image
image

**Comment by onyxcode** [comment]
Yeah I'll merge it later today.

**Pull request merged**
